.\" Copyright 1994-1995, Daniel Quinlan <Daniel.Quinlan@linux.org>
.\" Copyright 2002-2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright, Andries E. Brouwer <aeb@cwi.nl>
.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_sys_fs_inotify 5 (date) "Linux man-pages (unreleased)"
.SH NAME
/proc/sys/fs/inotify/ \- kernel variables related to inotify
.SH SYNOPSIS
.I /proc/sys/fs/inotify/
.SH DESCRIPTION
This directory contains files
.IR max_queued_events ", " max_user_instances ", and " max_user_watches ,
that can be used to limit the amount of kernel memory consumed by the
.BR inotify (7)
interface.
.SH HISTORY
Linux 2.6.13.
.SH SEE ALSO
.BR proc_sys_fs (5),
.BR inotify (7)
