.\" Copyright 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH sys_kernel_cgroup 5 (date) "Linux man-pages (unreleased)"
.SH NAME
/sys/kernel/cgroup/ \- Linux control groups
.SH SYNOPSIS
.I /sys/kernel/cgroup/
.SH DESCRIPTION
.TP
.IR /sys/kernel/cgroup/delegate " (since Linux 4.15)"
.\" commit 01ee6cfb1483fe57c9cbd8e73817dfbf9bacffd3
This file exports a list of the cgroups v2 files
(one per line) that are delegatable
(i.e., whose ownership should be changed to the user ID of the delegatee).
In the future, the set of delegatable files may change or grow,
and this file provides a way for the kernel to inform
user-space applications of which files must be delegated.
As at Linux 4.15, one sees the following when inspecting this file:
.IP
.in +4n
.EX
.RB $ " cat /sys/kernel/cgroup/delegate"
cgroup.procs
cgroup.subtree_control
cgroup.threads
.EE
.in
.TP
.IR /sys/kernel/cgroup/features " (since Linux 4.15)"
.\" commit 5f2e673405b742be64e7c3604ed4ed3ac14f35ce
Over time, the set of cgroups v2 features that are provided by the
kernel may change or grow,
or some features may not be enabled by default.
This file provides a way for user-space applications to discover what
features the running kernel supports and has enabled.
Features are listed one per line:
.IP
.in +4n
.EX
.RB $ " cat /sys/kernel/cgroup/features"
nsdelegate
memory_localevents
.EE
.in
.IP
The entries that can appear in this file are:
.RS
.TP
.IR memory_localevents " (since Linux 5.2)"
The kernel supports the
.I memory_localevents
mount option.
.TP
.IR nsdelegate " (since Linux 4.15)"
The kernel supports the
.I nsdelegate
mount option.
.TP
.IR memory_recursiveprot " (since Linux 5.7)"
.\" commit 8a931f801340c2be10552c7b5622d5f4852f3a36
The kernel supports the
.I memory_recursiveprot
mount option.
.RE
.SH STANDARDS
Linux.
.SH HISTORY
Linux 2.6.0.
.SH SEE ALSO
.BR sys_kernel (5),
.BR cgroups (7)
