.\" Copyright 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH sys_power 5 (date) "Linux man-pages (unreleased)"
.SH NAME
/sys/power/ \- power
.SH SYNOPSIS
.I /sys/power/
.SH DESCRIPTION
[To be documented]
.SH STANDARDS
Linux.
.SH HISTORY
Linux 2.6.0.
.SH SEE ALSO
.BR sysfs (5)
