.\" Copyright 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH sys_devices 5 (date) "Linux man-pages (unreleased)"
.SH NAME
/sys/devices/ \- device tree
.SH SYNOPSIS
.I /sys/devices/
.SH DESCRIPTION
This is a directory that contains a filesystem representation of
the kernel device tree,
which is a hierarchy of
.I device
structures within the kernel.
.SH STANDARDS
Linux.
.SH HISTORY
Linux 2.6.0.
.SH SEE ALSO
.BR sysfs (5)
