.\" Copyright 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH sysfs 5 (date) "Linux man-pages (unreleased)"
.SH NAME
sysfs \- a filesystem for exporting kernel objects
.SH DESCRIPTION
The
.B sysfs
filesystem is a pseudo-filesystem which provides an interface to
kernel data structures.
(More precisely, the files and directories in
.B sysfs
provide a view of the
.I kobject
structures defined internally within the kernel.)
The files under
.B sysfs
provide information about devices, kernel modules, filesystems,
and other kernel components.
.P
The
.B sysfs
filesystem is commonly mounted at
.IR /sys .
Typically, it is mounted automatically by the system,
but it can also be mounted manually using a command such as:
.P
.in +4n
.EX
mount \-t sysfs sysfs /sys
.EE
.in
.P
Many of the files in the
.B sysfs
filesystem are read-only,
but some files are writable, allowing kernel variables to be changed.
To avoid redundancy,
symbolic links are heavily used to connect entries across the filesystem tree.
.\"
.SS Files and directories
The following list describes some of the files and directories under the
.I /sys
hierarchy.
.TP
.I /sys/block/
See
.BR sys_block (5).
.TP
.I /sys/bus/
See
.BR sys_bus (5).
.TP
.I /sys/class/
See
.BR sys_class (5).
.TP
.I /sys/dev/
See
.BR sys_dev (5).
.TP
.I /sys/devices/
See
.BR sys_devices (5).
.TP
.I /sys/firmware/
See
.BR sys_firmware (5).
.TP
.I /sys/fs/
See
.BR sys_fs (5).
.TP
.I /sys/hypervisor/
See
.BR sys_hypervisor (5).
.TP
.I /sys/kernel/
See
.BR sys_kernel (5).
.TP
.I /sys/module/
See
.BR sys_module (5).
.TP
.I /sys/power
[To be documented]
.SH STANDARDS
Linux.
.SH HISTORY
Linux 2.6.0.
.SH NOTES
This manual page is incomplete, possibly inaccurate, and is the kind
of thing that needs to be updated very often.
.SH SEE ALSO
.BR proc (5),
.BR udev (7)
.P
P.\& Mochel (2005).
.IR "The sysfs filesystem" .
Proceedings of the 2005 Ottawa Linux Symposium.
.\" https://www.kernel.org/pub/linux/kernel/people/mochel/doc/papers/ols-2005/mochel.pdf
.P
The kernel source file
.I Documentation/filesystems/sysfs.rst
and various other files in
.I Documentation/ABI
and
.IR Documentation/*/sysfs.rst .
