.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH io_setup 3 (date) "Linux man-pages (unreleased)"
.SH NAME
io_setup \- create an asynchronous I/O context
.SH LIBRARY
Asynchronous I/O library
.RI ( libaio ,\~ \-laio )
.SH SYNOPSIS
.nf
.B #include <libaio.h>
.P
.BI long\~io_setup(unsigned\~int\~ n ", io_context_t\~*" ctx_idp );
.fi
.SH DESCRIPTION
.BR io_setup ()
creates an asynchronous I/O context suitable for concurrently processing
.I n
operations.
.SH RETURN VALUE
On success,
.BR io_setup ()
returns 0.
On error,
a negative error code is returned to indicate the error.
.SH ERRORS
See
.BR io_setup (2).
.SH STANDARDS
libaio.
.SH HISTORY
libaio.
.SH SEE ALSO
.BR io_setup (2),
.BR io (3),
.BR aio (7)
