'\" t
.\" Copyright 2004, Andries E. Brouwer <aeb@cwi.nl>
.\" Copyright 2020, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH lseek64 3 (date) "Linux man-pages (unreleased)"
.SH NAME
lseek64 \- reposition 64-bit read/write file offset
.SH LIBRARY
Standard C library
.RI ( libc ,\~ \-lc )
.SH SYNOPSIS
.nf
.BR "#define _LARGEFILE64_SOURCE" "     /* See feature_test_macros(7) */"
.B #include <sys/types.h>
.B #include <unistd.h>
.P
.BI "[[deprecated]] off64_t lseek64(int " fd ", off64_t " offset ", int " whence );
.fi
.SH DESCRIPTION
This function is equivalent to
.BR lseek (2)
if one compiles with
.P
.in +4n
.EX
#define _FILE_OFFSET_BITS 64
.EE
.in
.P
Use
.BR lseek (2)
instead.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lbx lb lb
l l l.
Interface	Attribute	Value
T{
.na
.nh
.BR lseek64 ()
T}	Thread safety	MT-Safe
.TE
.SH HISTORY
glibc 2.1.
.P
.BR lseek64 ()
is one of the functions that was specified in the Large File Summit (LFS)
specification that was completed in 1996.
The purpose of the specification was to provide transitional support
that allowed applications on 32-bit systems to access
files whose size exceeds that which can be represented with a 32-bit
.I off_t
type.
.SH SEE ALSO
.BR _llseek (2),
.BR lseek (2)
