'\" t
.\" Copyright 1993, David Metcalfe <david@prism.demon.co.uk>
.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH rawmemchr 3 (date) "Linux man-pages (unreleased)"
.SH NAME
rawmemchr \- memory raw search character
.SH LIBRARY
Standard C library
.RI ( libc ,\~ \-lc )
.SH SYNOPSIS
.nf
.BR "#define _GNU_SOURCE" "  /* See feature_test_macros(7) */"
.B #include <string.h>
.P
.BI "[[deprecated]] void *rawmemchr(const void *" s ", int " c );
.fi
.SH DESCRIPTION
The
.BR rawmemchr ()
function is similar to
.BR memchr (),
but it assumes
(i.e., the programmer knows for certain)
that an instance of
.I c
lies somewhere in the memory area starting at the location pointed to by
.IR s .
.P
If an instance of
.I c
is not found, the behavior is undefined.
Use either
.BR strlen (3)
or
.BR memchr (3)
instead.
.SH RETURN VALUE
The
.BR rawmemchr ()
function returns a pointer to the matching byte.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lbx lb lb
l l l.
Interface	Attribute	Value
T{
.na
.nh
.BR rawmemchr ()
T}	Thread safety	MT-Safe
.TE
.SH STANDARDS
GNU.
.SH HISTORY
glibc 2.1.
.SH SEE ALSO
.BR memchr (3),
.BR strlen (3),
.BR strnul (3)
