.TH chroot 8 (date) "GNU coreutils (unreleased)"
.SH NAME
chroot \- run command or interactive shell with special root directory
.SH SYNOPSIS
.SY chroot
.RI [ OPTION \~.\|.\|.\&]
.I NEWROOT
.RI [ COMMAND
.RI [ ARG \~.\|.\|.\&]]
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Run COMMAND with root directory set to NEWROOT.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chroot\-\-groups
\fB\-\-groups=G_LIST\fP
.UE
specify supplementary groups as g1,g2,..,gN
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chroot\-\-userspec
\fB\-\-userspec=USER:GROUP\fP
.UE
specify user and group (ID or name) to use
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chroot\-\-skip\-chdir
\fB\-\-skip\-chdir\fP
.UE
do not change working directory to '/'
.TP
.UR https://www.gnu.org/software/coreutils/chroot#chroot\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/chroot#chroot\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.PP
If no command is given, run '"$SHELL" \fB\-i\fR' (default: '/bin/sh \fB\-i\fR').
.SH EXIT STATUS
.TP
125
if the chroot command itself fails
.TP
126
if COMMAND is found but cannot be invoked
.TP
127
if COMMAND cannot be found
.TP
\-
the exit status of COMMAND otherwise
.SH AUTHOR
Written by Roland McGrath.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
General help using GNU software: <https://www.gnu.org/gethelp/>
.br
Report any translation bugs to <https://translationproject.org/team/>
.SH "SEE ALSO"
\fBchroot\fP(2)
.PP
.br
Full documentation <https://www.gnu.org/software/coreutils/chroot>
.br
or available locally via: info \(aq(coreutils) chroot invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
