.TH GREPC 1 2022-05-09 grepc "User commands"
.SH NAME
grepc \- find C declarations and definitions in source code
.SH SYNOPSIS
.B grepc
.RI [ option " ...]"
.I identifier
.SH DESCRIPTION
.MR grepc 1
searches for all C declarations and definitions of
.I identifier
in all .c and .h files under the current working directory.
.I identifier
is normally a C identifier,
but it is actually a PCRE pattern,
so it can be used to find complex patterns.
.SH OPTIONS
.TP
.B \-h
Output a help message and exit.
.TP
.BI \-x " extension"
Restrict the search to files ending with
.IR extension .
It is interpreted as a PCRE pattern.
Default:
.RB \(dq \e.[ch]$ \(dq.
.SH EXAMPLES
.EX
.RB \(ti/src/nginx/unit$ " grepc nxt_sprintf;"
\&
\&
\&./src/nxt_sprintf.h:15:

NXT_EXPORT u_char *nxt_cdecl nxt_sprintf(u_char *buf, u_char *end,
    const char *fmt, ...);
\&
\&
\&./src/nxt_sprintf.c:58:

u_char * nxt_cdecl
nxt_sprintf(u_char *buf, u_char *end, const char *fmt, ...)
{
    u_char   *p;
    va_list  args;

    va_start(args, fmt);
    p = nxt_vsprintf(buf, end, fmt, args);
    va_end(args);

    return p;
}
.EE
.SH AUTHORS
Originally written by
.MT alx.manpages@gmail.com
Alejandro Colomar
.ME .
.SH SEE ALSO
.MR pcregrep 1 ,
.MR pcresyntax 3 ,
.MR pcrepattern 3
.PP
Homepage:
.UR http://www.alejandro-colomar.es/\:src/\:alx/\:alx/\:grepc.git
.UE
