.TH basenc 1 (date) "GNU coreutils (unreleased)"
.SH NAME
basenc \- Encode/decode data and print to standard output
.SH SYNOPSIS
.SY basenc
.RI [ OPTION \~.\|.\|.\&]
.RI [ FILE ]
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
basenc encode or decode FILE, or standard input, to standard output.
.PP
With no FILE, or when FILE is \-, read standard input.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#basenc\-\-base64
\fB\-\-base64\fP
.UE
same as 'base64' program (RFC4648 section 4)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#basenc\-\-base64url
\fB\-\-base64url\fP
.UE
file\- and url\-safe base64 (RFC4648 section 5)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#basenc\-\-base58
\fB\-\-base58\fP
.UE
visually unambiguous base58 encoding
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#basenc\-\-base32
\fB\-\-base32\fP
.UE
same as 'base32' program (RFC4648 section 6)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#basenc\-\-base32hex
\fB\-\-base32hex\fP
.UE
extended hex alphabet base32 (RFC4648 section 7)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#basenc\-\-base16
\fB\-\-base16\fP
.UE
hex encoding (RFC4648 section 8)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#basenc\-\-base2msbf
\fB\-\-base2msbf\fP
.UE
bit string with most significant bit (msb) first
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#basenc\-\-base2lsbf
\fB\-\-base2lsbf\fP
.UE
bit string with least significant bit (lsb) first
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#basenc\-d
\fB\-d, \-\-decode\fP
.UE
decode data
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#basenc\-i
\fB\-i, \-\-ignore\-garbage\fP
.UE
when decoding, ignore non\-alphabet characters
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#basenc\-w
\fB\-w, \-\-wrap=\,COLS\fP
.UE
wrap encoded lines after COLS character (default 76).
Use 0 to disable line wrapping
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#basenc\-\-z85
\fB\-\-z85\fP
.UE
ascii85\-like encoding (ZeroMQ spec:32/Z85);
when encoding, input length must be a multiple of 4;
when decoding, input length must be a multiple of 5
.TP
.UR https://www.gnu.org/software/coreutils/basenc#basenc\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/basenc#basenc\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.PP
When decoding, the input may contain newlines in addition to the bytes of
the formal alphabet.  Use \fB\-\-ignore\-garbage\fR to attempt to recover
from any other non\-alphabet bytes in the encoded stream.
.SH "ENCODING EXAMPLES"
.PP
.nf
.RS
$ printf '\\376\\117\\202' | basenc \-\-base64
/k+C

$ printf '\\376\\117\\202' | basenc \-\-base64url
_k-C

$ printf '\\376\\117\\202' | basenc \-\-base32
7ZHYE===

$ printf '\\376\\117\\202' | basenc \-\-base32hex
VP7O4===

$ printf '\\376\\117\\202' | basenc \-\-base16
FE4F82

$ printf '\\376\\117\\202' | basenc \-\-base2lsbf
011111111111001001000001

$ printf '\\376\\117\\202' | basenc \-\-base2msbf
111111100100111110000010

$ printf '\\376\\117\\202\\000' | basenc \-\-z85
@.FaC
.RE
.fi
.SH AUTHOR
Written by Simon Josefsson and Assaf Gordon.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
.UR https://www.gnu.org/software/coreutils/basenc
Full documentation online
.UE
.br
or available locally via: info \(aq(coreutils) basenc invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
