.TH cat 1 (date) "GNU coreutils (unreleased)"
.SH NAME
cat \- concatenate files and print on the standard output
.SH SYNOPSIS
.SY cat
.RI [ OPTION \~.\|.\|.\&]
.RI [ FILE \~.\|.\|.\&]
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Concatenate FILE(s) to standard output.
.PP
With no FILE, or when FILE is \-, read standard input.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cat\-A
\fB\-A, \-\-show\-all\fP
.UE
equivalent to \fB\-vET\fR
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cat\-b
\fB\-b, \-\-number\-nonblank\fP
.UE
number nonempty output lines, overrides \fB\-n\fR
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cat\-e
\fB\-e\fP
.UE
equivalent to \fB\-vE\fR
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cat\-E
\fB\-E, \-\-show\-ends\fP
.UE
display $ or ^M$ at end of each line
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cat\-n
\fB\-n, \-\-number\fP
.UE
number all output lines
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cat\-s
\fB\-s, \-\-squeeze\-blank\fP
.UE
suppress repeated empty output lines
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cat\-t
\fB\-t\fP
.UE
equivalent to \fB\-vT\fR
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cat\-T
\fB\-T, \-\-show\-tabs\fP
.UE
display TAB characters as ^I
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cat\-u
\fB\-u\fP
.UE
(ignored)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cat\-v
\fB\-v, \-\-show\-nonprinting\fP
.UE
use ^ and M\- notation, except for LFD and TAB
.TP
.UR https://www.gnu.org/software/coreutils/cat#cat\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/cat#cat\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.SH EXAMPLES
.TP
cat f \- g
Output f's contents, then standard input, then g's contents.
.TP
cat
Copy standard input to standard output.
.SH AUTHOR
Written by Torbjorn Granlund and Richard M. Stallman.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
GNU coreutils home page: <https://www.gnu.org/software/coreutils/>
.br
General help using GNU software: <https://www.gnu.org/gethelp/>
.br
Report any translation bugs to <https://translationproject.org/team/>
.SH "SEE ALSO"
\fBtac\fP(1)
.PP
.br
Full documentation <https://www.gnu.org/software/coreutils/cat>
.br
or available locally via: info \(aq(coreutils) cat invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
