.TH chcon 1 (date) "GNU coreutils (unreleased)"
.SH NAME
chcon \- change file security context
.SH SYNOPSIS
.SY chcon
.RI [ OPTION \~.\|.\|.\&]
.I CONTEXT
.IR FILE \~.\|.\|.\&
.YS
.SY chcon
.RI [ OPTION \~.\|.\|.\&]
.RB [ \-u
.IR USER ]
.RB [ \-r
.IR ROLE ]
.RB [ \-l
.IR RANGE ]
.RB [ \-t
.IR TYPE ]
.IR FILE \~.\|.\|.\&
.YS
.SY chcon
.RI [ OPTION \~.\|.\|.\&]
.BI \-\-reference= RFILE
.IR FILE \~.\|.\|.\&
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Change the SELinux security context of each FILE to CONTEXT.
With \fB\-\-reference\fR, change the security context of each FILE to that of RFILE.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chcon\-\-dereference
\fB\-\-dereference\fP
.UE
affect the referent of each symbolic link (this is
the default), rather than the symbolic link itself
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chcon\-h
\fB\-h, \-\-no\-dereference\fP
.UE
affect symbolic links instead of any referenced file
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chcon\-u
\fB\-u, \-\-user=\,USER\fP
.UE
set user USER in the target security context
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chcon\-r
\fB\-r, \-\-role=\,ROLE\fP
.UE
set role ROLE in the target security context
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chcon\-t
\fB\-t, \-\-type=\,TYPE\fP
.UE
set type TYPE in the target security context
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chcon\-l
\fB\-l, \-\-range=\,RANGE\fP
.UE
set range RANGE in the target security context
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chcon\-\-no\-preserve\-root
\fB\-\-no\-preserve\-root\fP
.UE
do not treat '/' specially (the default)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chcon\-\-preserve\-root
\fB\-\-preserve\-root\fP
.UE
fail to operate recursively on '/'
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chcon\-\-reference
\fB\-\-reference=RFILE\fP
.UE
use RFILE's security context rather than specifying a CONTEXT value
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chcon\-R
\fB\-R, \-\-recursive\fP
.UE
operate on files and directories recursively
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chcon\-v
\fB\-v, \-\-verbose\fP
.UE
output a diagnostic for every file processed
.PP
The following options modify how a hierarchy is traversed when the \fB\-R\fR
option is also specified.  If more than one is specified, only the final
one takes effect. \fB\-P\fR is the default.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chcon\-H
\fB\-H\fP
.UE
if a command line argument is a symlink to a directory, traverse it
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chcon\-L
\fB\-L\fP
.UE
traverse every symbolic link to a directory encountered
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chcon\-P
\fB\-P\fP
.UE
do not traverse any symbolic links
.TP
.UR https://www.gnu.org/software/coreutils/chcon#chcon\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/chcon#chcon\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.SH AUTHOR
Written by Russell Coker and Jim Meyering.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
General help using GNU software: <https://www.gnu.org/gethelp/>
.br
Report any translation bugs to <https://translationproject.org/team/>
.SH "SEE ALSO"
Full documentation <https://www.gnu.org/software/coreutils/chcon>
.br
or available locally via: info \(aq(coreutils) chcon invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
