.TH chgrp 1 (date) "GNU coreutils (unreleased)"
.SH NAME
chgrp \- change group ownership
.SH SYNOPSIS
.SY chgrp
.RI [ OPTION \~.\|.\|.\&]
.I GROUP
.IR FILE \~.\|.\|.\&
.YS
.SY chgrp
.RI [ OPTION \~.\|.\|.\&]
.BI \-\-reference= RFILE
.IR FILE \~.\|.\|.\&
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Change the group of each FILE to GROUP.
With \fB\-\-reference\fR, change the group of each FILE to that of RFILE.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chgrp\-c
\fB\-c, \-\-changes\fP
.UE
like verbose but report only when a change is made
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chgrp\-f
\fB\-f, \-\-silent, \-\-quiet\fP
.UE
suppress most error messages
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chgrp\-v
\fB\-v, \-\-verbose\fP
.UE
output a diagnostic for every file processed
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chgrp\-\-dereference
\fB\-\-dereference\fP
.UE
affect the referent of each symbolic link (this is
the default), rather than the symbolic link itself
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chgrp\-h
\fB\-h, \-\-no\-dereference\fP
.UE
affect symbolic links instead of any referenced file;
useful only on systems that can change the ownership of a symlink
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chgrp\-\-from
\fB\-\-from=CURRENT_OWNER:CURRENT_GROUP\fP
.UE
change the ownership of each file only if its
current owner and/or group match those specified here.
Either may be omitted, in which case a match
is not required for the omitted attribute
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chgrp\-\-no\-preserve\-root
\fB\-\-no\-preserve\-root\fP
.UE
do not treat '/' specially (the default)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chgrp\-\-preserve\-root
\fB\-\-preserve\-root\fP
.UE
fail to operate recursively on '/'
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chgrp\-\-reference
\fB\-\-reference=RFILE\fP
.UE
use RFILE's ownership rather than specifying values.
RFILE is always dereferenced if a symbolic link.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chgrp\-R
\fB\-R, \-\-recursive\fP
.UE
operate on files and directories recursively
.PP
The following options modify how a hierarchy is traversed when the \fB\-R\fR
option is also specified.  If more than one is specified, only the final
one takes effect. \fB\-P\fR is the default.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chgrp\-H
\fB\-H\fP
.UE
if a command line argument is a symlink to a directory, traverse it
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chgrp\-L
\fB\-L\fP
.UE
traverse every symbolic link to a directory encountered
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#chgrp\-P
\fB\-P\fP
.UE
do not traverse any symbolic links
.TP
.UR https://www.gnu.org/software/coreutils/chgrp#chgrp\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/chgrp#chgrp\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.SH EXAMPLES
.TP
chgrp staff /u
Change the group of /u to "staff".
.TP
chgrp \-hR staff /u
Change the group of /u and subfiles to "staff".
.SH AUTHOR
Written by David MacKenzie and Jim Meyering.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
GNU coreutils home page: <https://www.gnu.org/software/coreutils/>
.br
General help using GNU software: <https://www.gnu.org/gethelp/>
.br
Report any translation bugs to <https://translationproject.org/team/>
.SH "SEE ALSO"
\fBchown\fP(1), \fBchown\fP(2)
.PP
.br
Full documentation <https://www.gnu.org/software/coreutils/chgrp>
.br
or available locally via: info \(aq(coreutils) chgrp invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
