.TH comm 1 (date) "GNU coreutils (unreleased)"
.SH NAME
comm \- compare two sorted files line by line
.SH SYNOPSIS
.SY comm
.RI [ OPTION \~.\|.\|.\&]
.I FILE1
.I FILE2
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Compare sorted files FILE1 and FILE2 line by line.
.PP
When FILE1 or FILE2 (not both) is \-, read standard input.
.PP
With no options, produce three\-column output.  Column one contains
lines unique to FILE1, column two contains lines unique to FILE2,
and column three contains lines common to both files.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#comm\-1
\fB\-1\fP
.UE
suppress column 1 (lines unique to FILE1)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#comm\-2
\fB\-2\fP
.UE
suppress column 2 (lines unique to FILE2)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#comm\-3
\fB\-3\fP
.UE
suppress column 3 (lines that appear in both files)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#comm\-\-check\-order
\fB\-\-check\-order\fP
.UE
check that the input is correctly sorted,
even if all input lines are pairable
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#comm\-\-nocheck\-order
\fB\-\-nocheck\-order\fP
.UE
do not check that the input is correctly sorted
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#comm\-\-output\-delimiter
\fB\-\-output\-delimiter=STR\fP
.UE
separate columns with STR
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#comm\-\-total
\fB\-\-total\fP
.UE
output a summary
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#comm\-z
\fB\-z, \-\-zero\-terminated\fP
.UE
line delimiter is NUL, not newline
.TP
.UR https://www.gnu.org/software/coreutils/comm#comm\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/comm#comm\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.PP
Comparisons honor the rules specified by 'LC_COLLATE'.
.SH EXAMPLES
.TP
comm \-12 file1 file2
Print only lines present in both file1 and file2.
.TP
comm \-3 file1 file2
Print lines in file1 not in file2, and vice versa.
.SH AUTHOR
Written by Richard M. Stallman and David MacKenzie.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
\fBjoin\fP(1), \fBuniq\fP(1)
.PP
.br
.UR https://www.gnu.org/software/coreutils/comm
Full documentation online
.UE
.br
or available locally via: info \(aq(coreutils) comm invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
SPDX-License-Identifier:
.UR https://gnu.org/licenses/gpl.html
GPL-3.0-or-later
.UE
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
