.TH cp 1 (date) "GNU coreutils (unreleased)"
.SH NAME
cp \- copy files and directories
.SH SYNOPSIS
.SY cp
.RI [ OPTION \~.\|.\|.\&]
.RB [ \-T ]
.I SOURCE
.I DEST
.YS
.SY cp
.RI [ OPTION \~.\|.\|.\&]
.IR SOURCE \~.\|.\|.\&
.I DIRECTORY
.YS
.SY cp
.RI [ OPTION \~.\|.\|.\&]
.BI -t\~ DIRECTORY
.IR SOURCE \~.\|.\|.\&
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Copy SOURCE to DEST, or multiple SOURCE(s) to DIRECTORY.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-a
\fB\-a, \-\-archive\fP
.UE
same as \fB\-dR\fR \fB\-\-preserve\fR=\fI\,all\/\fR
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-\-attributes\-only
\fB\-\-attributes\-only\fP
.UE
don't copy the file data, just the attributes
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-\-backup
\fB\-\-backup[=CONTROL]\fP
.UE
make a backup of each existing destination file
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-b
\fB\-b\fP
.UE
like \fB\-\-backup\fR but does not accept an argument
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-\-copy\-contents
\fB\-\-copy\-contents\fP
.UE
copy contents of special files when recursive
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-d
\fB\-d\fP
.UE
same as \fB\-\-no\-dereference\fR \fB\-\-preserve\fR=\fI\,links\/\fR
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-\-debug
\fB\-\-debug\fP
.UE
explain how a file is copied.  Implies \fB\-v\fR
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-f
\fB\-f, \-\-force\fP
.UE
if an existing destination file cannot be opened, remove it and try
again (this option is ignored when the \fB\-n\fR option is also used)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-i
\fB\-i, \-\-interactive\fP
.UE
prompt before overwrite (overrides a previous \fB\-n\fR option)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-H
\fB\-H\fP
.UE
follow command\-line symbolic links in SOURCE
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-L
\fB\-L, \-\-dereference\fP
.UE
always follow symbolic links in SOURCE
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-P
\fB\-P, \-\-no\-dereference\fP
.UE
never follow symbolic links in SOURCE
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-\-keep\-directory\-symlink
\fB\-\-keep\-directory\-symlink\fP
.UE
follow existing symlinks to directories
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-l
\fB\-l, \-\-link\fP
.UE
hard link files instead of copying
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-n
\fB\-n, \-\-no\-clobber\fP
.UE
(deprecated) silently skip existing files.  See also \fB\-\-update\fR
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-p
\fB\-p\fP
.UE
same as \fB\-\-preserve\fR=\fI\,mode,ownership,timestamps\/\fR
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-\-preserve
\fB\-\-preserve[=ATTR_LIST]\fP
.UE
preserve the specified attributes
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-\-no\-preserve
\fB\-\-no\-preserve=ATTR_LIST\fP
.UE
don't preserve the specified attributes
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-\-parents
\fB\-\-parents\fP
.UE
use full source file name under DIRECTORY
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-R
\fB\-R, \-r, \-\-recursive\fP
.UE
copy directories recursively
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-\-reflink
\fB\-\-reflink[=WHEN]\fP
.UE
control clone/CoW copies. See below
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-\-remove\-destination
\fB\-\-remove\-destination\fP
.UE
remove each existing destination file before attempting to open it
(contrast with \fB\-\-force\fR)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-\-sparse
\fB\-\-sparse=WHEN\fP
.UE
control creation of sparse files. See below
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-\-strip\-trailing\-slashes
\fB\-\-strip\-trailing\-slashes\fP
.UE
remove any trailing slashes from each SOURCE argument
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-s
\fB\-s, \-\-symbolic\-link\fP
.UE
make symbolic links instead of copying
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-S
\fB\-S, \-\-suffix=\,SUFFIX\fP
.UE
override the usual backup suffix
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-t
\fB\-t, \-\-target\-directory=\,DIRECTORY\fP
.UE
copy all SOURCE arguments into DIRECTORY
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-T
\fB\-T, \-\-no\-target\-directory\fP
.UE
treat DEST as a normal file
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-\-update
\fB\-\-update[=UPDATE]\fP
.UE
control which existing files are updated;
UPDATE={all,none,none\-fail,older(default)}
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-u
\fB\-u\fP
.UE
equivalent to \fB\-\-update\fR[=\fI\,older\/\fR].  See below
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-v
\fB\-v, \-\-verbose\fP
.UE
explain what is being done
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-x
\fB\-x, \-\-one\-file\-system\fP
.UE
stay on this file system
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-Z
\fB\-Z\fP
.UE
set SELinux security context of destination file to default type
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#cp\-\-context
\fB\-\-context[=CTX]\fP
.UE
like \fB\-Z\fR, or if CTX is specified then set the
SELinux or SMACK security context to CTX
.TP
.UR https://www.gnu.org/software/coreutils/cp#cp\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/cp#cp\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.PP
ATTR_LIST is a comma\-separated list of attributes. Attributes are 'mode' for
permissions (including any ACL and xattr permissions), 'ownership' for user
and group, 'timestamps' for file timestamps, 'links' for hard links, 'context'
for security context, 'xattr' for extended attributes, and 'all' for all
attributes.
.PP
By default, sparse SOURCE files are detected by a crude heuristic and the
corresponding DEST file is made sparse as well.  That is the behavior
selected by \fB\-\-sparse\fR=\fI\,auto\/\fR.  Specify \fB\-\-sparse\fR=\fI\,always\/\fR to create a sparse DEST
file whenever the SOURCE file contains a long enough sequence of zero bytes.
Use \fB\-\-sparse\fR=\fI\,never\/\fR to inhibit creation of sparse files.
.PP
UPDATE controls which existing files in the destination are replaced.
\&'all' is the default operation when an \fB\-\-update\fR option is not specified,
and results in all existing files in the destination being replaced.
\&'none' is like the \fB\-\-no\-clobber\fR option, in that no files in the
destination are replaced, and skipped files do not induce a failure.
\&'none\-fail' also ensures no files are replaced in the destination,
but any skipped files are diagnosed and induce a failure.
\&'older' is the default operation when \fB\-\-update\fR is specified, and results
in files being replaced if they're older than the corresponding source file.
.PP
By default or with \fB\-\-reflink\fR=\fI\,auto\/\fR, cp will try a lightweight copy, where the
data blocks are copied only when modified, falling back to a standard copy
if this is not possible.  With \fB\-\-reflink\fR[=\fI\,always\/\fR] cp will fail if CoW is not
supported, while \fB\-\-reflink\fR=\fI\,never\/\fR ensures a standard copy is performed.
.PP
The backup suffix is '~', unless set with \fB\-\-suffix\fR or SIMPLE_BACKUP_SUFFIX.
The version control method may be selected via the \fB\-\-backup\fR option or through
the VERSION_CONTROL environment variable.  Here are the values:
.TP
none, off
never make backups (even if \fB\-\-backup\fR is given)
.TP
numbered, t
make numbered backups
.TP
existing, nil
numbered if numbered backups exist, simple otherwise
.TP
simple, never
always make simple backups
.PP
As a special case, cp makes a backup of SOURCE when the force and backup
options are given and SOURCE and DEST are the same name for an existing,
regular file.
.SH AUTHOR
Written by Torbjorn Granlund, David MacKenzie, and Jim Meyering.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
\fBinstall\fP(1)
.PP
.br
.UR https://www.gnu.org/software/coreutils/cp
Full documentation online
.UE
.br
or available locally via: info \(aq(coreutils) cp invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
