.TH dirname 1 (date) "GNU coreutils (unreleased)"
.SH NAME
dirname \- strip last component from file name
.SH SYNOPSIS
.SY dirname
.RI [ OPTION ]
.IR NAME \~.\|.\|.\&
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Output each NAME with its last non\-slash component and trailing slashes
removed; if NAME contains no /'s, output '.' (meaning the current directory).
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#dirname\-z
\fB\-z, \-\-zero\fP
.UE
end each output line with NUL, not newline
.TP
.UR https://www.gnu.org/software/coreutils/dirname#dirname\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/dirname#dirname\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.SH EXAMPLES
.TP
dirname /usr/bin/
\-> "/usr"
.TP
dirname dir1/str dir2/str
\-> "dir1" followed by "dir2"
.TP
dirname stdio.h
\-> "."
.SH AUTHOR
Written by David MacKenzie and Jim Meyering.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
General help using GNU software: <https://www.gnu.org/gethelp/>
.br
Report any translation bugs to <https://translationproject.org/team/>
.SH "SEE ALSO"
\fBbasename\fP(1), \fBreadlink\fP(1)
.PP
.br
Full documentation <https://www.gnu.org/software/coreutils/dirname>
.br
or available locally via: info \(aq(coreutils) dirname invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
