.TH echo 1 (date) "GNU coreutils (unreleased)"
.SH NAME
echo \- display a line of text
.SH SYNOPSIS
.SY echo
.RI [ SHORT-OPTION \~.\|.\|.\&]
.RI [ STRING \~.\|.\|.\&]
.YS
.SY echo
.I LONG-OPTION
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Echo the STRING(s) to standard output.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#echo\-n
\fB\-n\fP
.UE
do not output the trailing newline
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#echo\-e
\fB\-e\fP
.UE
enable interpretation of backslash escapes
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#echo\-E
\fB\-E\fP
.UE
disable interpretation of backslash escapes (default)
.TP
.UR https://www.gnu.org/software/coreutils/echo#echo\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/echo#echo\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.PP
If \fB\-e\fR is in effect, the following sequences are recognized:
.TP
\e\e
backslash
.TP
\ea
alert (BEL)
.TP
\eb
backspace
.TP
\ec
produce no further output
.TP
\ee
escape
.TP
\ef
form feed
.TP
\en
new line
.TP
\er
carriage return
.TP
\et
horizontal tab
.TP
\ev
vertical tab
.TP
\e0NNN
byte with octal value NNN (1 to 3 digits)
.TP
\exHH
byte with hexadecimal value HH (1 to 2 digits)
.PP
Your shell may have its own version of echo, which usually supersedes
the version described here.  Please refer to your shell's documentation
for details about the options it supports.
.PP
Consider using the \fBprintf\fP(1) command instead,
as it avoids problems when outputting option\-like strings.
.SH AUTHOR
Written by Brian Fox and Chet Ramey.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
\fBprintf\fP(1)
.PP
.br
.UR https://www.gnu.org/software/coreutils/echo
Full documentation online
.UE
.br
or available locally via: info \(aq(coreutils) echo invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
SPDX-License-Identifier:
.UR https://gnu.org/licenses/gpl.html
GPL-3.0-or-later
.UE
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
