.TH factor 1 (date) "GNU coreutils (unreleased)"
.SH NAME
factor \- factor numbers
.SH SYNOPSIS
.SY factor
.RI [ OPTION ]
.RI [ NUMBER \~.\|.\|.\&]
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Print the prime factors of each specified integer NUMBER.  If none
are specified on the command line, read them from standard input.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#factor\-h
\fB\-h, \-\-exponents\fP
.UE
print repeated factors in form p^e unless e is 1
.TP
.UR https://www.gnu.org/software/coreutils/factor#factor\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/factor#factor\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.SH AUTHOR
Written by Paul Rubin, Torbjorn Granlund, and Niels Moller.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
.UR https://www.gnu.org/software/coreutils/factor
Full documentation online
.UE
.br
or available locally via: info \(aq(coreutils) factor invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
