.TH false 1 (date) "GNU coreutils (unreleased)"
.SH NAME
false \- do nothing, unsuccessfully
.SH SYNOPSIS
.SY false
.RI [ "ignored command line arguments" ]
.YS
.SY false
.I OPTION
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Exit with a status code indicating failure.
.TP
.UR https://www.gnu.org/software/coreutils/false#false\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/false#false\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.PP
Your shell may have its own version of false, which usually supersedes
the version described here.  Please refer to your shell's documentation
for details about the options it supports.
.SH AUTHOR
Written by Jim Meyering.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
Full documentation <https://www.gnu.org/software/coreutils/false>
.br
or available locally via: info \(aq(coreutils) false invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
