.TH groups 1 (date) "GNU coreutils (unreleased)"
.SH NAME
groups \- print the groups a user is in
.SH SYNOPSIS
.SY groups
.RI [ OPTION \~.\|.\|.\&]
.RI [ USERNAME \~.\|.\|.\&]
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Print group memberships for each USERNAME or, if no USERNAME is specified, for
the current process (which may differ if the groups database has changed).
.TP
.UR https://www.gnu.org/software/coreutils/groups#groups\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/groups#groups\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.SH AUTHOR
Written by David MacKenzie and James Youngman.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to <https://translationproject.org/team/>
.SH "SEE ALSO"
\fBgetent\fP(1)
.PP
.br
Full documentation <https://www.gnu.org/software/coreutils/groups>
.br
or available locally via: info \(aq(coreutils) groups invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
