.TH head 1 (date) "GNU coreutils (unreleased)"
.SH NAME
head \- output the first part of files
.SH SYNOPSIS
.SY head
.RI [ OPTION \~.\|.\|.\&]
.RI [ FILE \~.\|.\|.\&]
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Print the first 10 lines of each FILE to standard output.
With more than one FILE, precede each with a header giving the file name.
.PP
With no FILE, or when FILE is \-, read standard input.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#head\-c
\fB\-c, \-\-bytes=\,[\-]NUM\fP
.UE
print the first NUM bytes of each file;
with the leading '\-', print all but the last NUM bytes of each file
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#head\-n
\fB\-n, \-\-lines=\,[\-]NUM\fP
.UE
print the first NUM lines instead of the first 10;
with the leading '\-', print all but the last NUM lines of each file
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#head\-q
\fB\-q, \-\-quiet, \-\-silent\fP
.UE
never print headers giving file names
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#head\-v
\fB\-v, \-\-verbose\fP
.UE
always print headers giving file names
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#head\-z
\fB\-z, \-\-zero\-terminated\fP
.UE
line delimiter is NUL, not newline
.TP
.UR https://www.gnu.org/software/coreutils/head#head\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/head#head\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.PP
NUM may have a multiplier suffix:
b 512, kB 1000, K 1024, MB 1000*1000, M 1024*1024,
GB 1000*1000*1000, G 1024*1024*1024, and so on for T, P, E, Z, Y, R, Q.
Binary prefixes can be used, too: KiB=K, MiB=M, and so on.
.SH AUTHOR
Written by David MacKenzie and Jim Meyering.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
\fBtail\fP(1)
.PP
.br
Full documentation <https://www.gnu.org/software/coreutils/head>
.br
or available locally via: info \(aq(coreutils) head invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
