.TH id 1 (date) "GNU coreutils (unreleased)"
.SH NAME
id \- print real and effective user and group IDs
.SH SYNOPSIS
.SY id
.RI [ OPTION \~.\|.\|.\&]
.RI [ USER \~.\|.\|.\&]
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Print user and group information for each specified USER,
or (when USER omitted) for the current process.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#id\-a
\fB\-a\fP
.UE
ignore, for compatibility with other versions
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#id\-Z
\fB\-Z, \-\-context\fP
.UE
print only the security context of the process
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#id\-g
\fB\-g, \-\-group\fP
.UE
print only the effective group ID
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#id\-G
\fB\-G, \-\-groups\fP
.UE
print all group IDs
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#id\-n
\fB\-n, \-\-name\fP
.UE
print a name instead of a number, for \fB\-u\fR,\-g,\-G
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#id\-r
\fB\-r, \-\-real\fP
.UE
print the real ID instead of the effective ID, with \fB\-u\fR,\-g,\-G
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#id\-u
\fB\-u, \-\-user\fP
.UE
print only the effective user ID
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#id\-z
\fB\-z, \-\-zero\fP
.UE
delimit entries with NUL characters, not whitespace;
not permitted in default format
.TP
.UR https://www.gnu.org/software/coreutils/id#id\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/id#id\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.PP
Without any OPTION, print some useful set of identified information.
.SH AUTHOR
Written by Arnold Robbins and David MacKenzie.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
.UR https://www.gnu.org/software/coreutils/id
Full documentation online
.UE
.br
or available locally via: info \(aq(coreutils) id invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
SPDX-License-Identifier:
.UR https://gnu.org/licenses/gpl.html
GPL-3.0-or-later
.UE
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
