.TH link 1 (date) "GNU coreutils (unreleased)"
.SH NAME
link \- call the link function to create a link to a file
.SH SYNOPSIS
.SY link
.I FILE1
.I FILE2
.YS
.SY link
.I OPTION
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Call the link function to create a link named FILE2 to an existing FILE1.
.TP
.UR https://www.gnu.org/software/coreutils/link#link\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/link#link\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.SH AUTHOR
Written by Michael Stone.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
\fBlink\fP(2)
.PP
.br
Full documentation <https://www.gnu.org/software/coreutils/link>
.br
or available locally via: info \(aq(coreutils) link invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
