.TH ln 1 (date) "GNU coreutils (unreleased)"
.SH NAME
ln \- make links between files
.SH SYNOPSIS
.SY ln
.RI [ OPTION \~.\|.\|.\&]
.RB [ \-T ]
.I TARGET
.I LINK_NAME
.YS
.SY ln
.RI [ OPTION \~.\|.\|.\&]
.I TARGET
.YS
.SY ln
.RI [ OPTION \~.\|.\|.\&]
.IR TARGET \~.\|.\|.\&
.I DIRECTORY
.YS
.SY ln
.RI [ OPTION \~.\|.\|.\&]
.BI \-t\~ DIRECTORY
.IR TARGET \~.\|.\|.\&
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
In the 1st form, create a link to TARGET with the name LINK_NAME.
In the 2nd form, create a link to TARGET in the current directory.
In the 3rd and 4th forms, create links to each TARGET in DIRECTORY.
Create hard links by default, symbolic links with \fB\-\-symbolic\fR.
By default, each destination (name of new link) should not already exist.
When creating hard links, each TARGET must exist.  Symbolic links
can hold arbitrary text; if later resolved, a relative link is
interpreted in relation to its parent directory.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#ln\-\-backup
\fB\-\-backup[=CONTROL]\fP
.UE
make a backup of each existing destination file
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#ln\-b
\fB\-b\fP
.UE
like \fB\-\-backup\fR but does not accept an argument
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#ln\-d
\fB\-d, \-F, \-\-directory\fP
.UE
allow the superuser to attempt to hard link directories,
if supported by the system
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#ln\-f
\fB\-f, \-\-force\fP
.UE
remove existing destination files
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#ln\-i
\fB\-i, \-\-interactive\fP
.UE
prompt whether to remove destinations
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#ln\-L
\fB\-L, \-\-logical\fP
.UE
dereference TARGETs that are symbolic links
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#ln\-n
\fB\-n, \-\-no\-dereference\fP
.UE
treat LINK_NAME as a normal file
if it is a symbolic link to a directory
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#ln\-P
\fB\-P, \-\-physical\fP
.UE
make hard links directly to symbolic links
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#ln\-r
\fB\-r, \-\-relative\fP
.UE
with \fB\-s\fR, create links relative to link location
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#ln\-s
\fB\-s, \-\-symbolic\fP
.UE
make symbolic links instead of hard links
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#ln\-S
\fB\-S, \-\-suffix=\,SUFFIX\fP
.UE
override the usual backup suffix
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#ln\-t
\fB\-t, \-\-target\-directory=\,DIRECTORY\fP
.UE
specify the DIRECTORY in which to create the links
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#ln\-T
\fB\-T, \-\-no\-target\-directory\fP
.UE
treat LINK_NAME as a normal file always
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#ln\-v
\fB\-v, \-\-verbose\fP
.UE
print name of each linked file
.TP
.UR https://www.gnu.org/software/coreutils/ln#ln\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/ln#ln\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.PP
The backup suffix is '~', unless set with \fB\-\-suffix\fR or SIMPLE_BACKUP_SUFFIX.
The version control method may be selected via the \fB\-\-backup\fR option or through
the VERSION_CONTROL environment variable.  Here are the values:
.TP
none, off
never make backups (even if \fB\-\-backup\fR is given)
.TP
numbered, t
make numbered backups
.TP
existing, nil
numbered if numbered backups exist, simple otherwise
.TP
simple, never
always make simple backups
.PP
Using \fB\-s\fR ignores \fB\-L\fR and \fB\-P\fR.  Otherwise, the last option specified controls
behavior when a TARGET is a symbolic link, defaulting to \fB\-P\fR.
.SH AUTHOR
Written by Mike Parker and David MacKenzie.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
General help using GNU software: <https://www.gnu.org/gethelp/>
.br
Report any translation bugs to <https://translationproject.org/team/>
.SH "SEE ALSO"
\fBlink\fP(2), \fBsymlink\fP(2)
.PP
.br
Full documentation <https://www.gnu.org/software/coreutils/ln>
.br
or available locally via: info \(aq(coreutils) ln invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
