.TH LOGNAME "1" "March 2026" "GNU coreutils (unreleased)"
.SH NAME
logname \- print user\'s login name
.SH SYNOPSIS
.B logname
[\fI\,OPTION\/\fR]
.SH DESCRIPTION
.\" Add any additional description here
.PP
Print the user's login name.
.TP
\X'tty: link https://www.gnu.org/software/coreutils/logname#logname--help'\fB\-\-help\fP\X'tty: link'
display this help and exit
.TP
\X'tty: link https://www.gnu.org/software/coreutils/logname#logname--version'\fB\-\-version\fP\X'tty: link'
output version information and exit
.SH AUTHOR
Written by David MacKenzie.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
GNU coreutils home page: <https://www.gnu.org/software/coreutils/>
.br
General help using GNU software: <https://www.gnu.org/gethelp/>
.br
Report any translation bugs to <https://translationproject.org/team/>
.SH "SEE ALSO"
\fBgetlogin\fP(3)
.PP
.br
Full documentation <https://www.gnu.org/software/coreutils/logname>
.br
or available locally via: info \(aq(coreutils) logname invocation\(aq
.PP
.br
Packaged by Devuan (9.10\-1devuan1)
.br
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
