.TH mkdir 1 (date) "GNU coreutils (unreleased)"
.SH NAME
mkdir \- make directories
.SH SYNOPSIS
.SY mkdir
.RI [ OPTION \~.\|.\|.\&]
.IR DIRECTORY \~.\|.\|.\&
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Create the DIRECTORY(ies), if they do not already exist.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mkdir\-m
\fB\-m, \-\-mode=\,MODE\fP
.UE
set file mode (as in chmod), not a=rwx \- umask
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mkdir\-p
\fB\-p, \-\-parents\fP
.UE
no error if existing, make parent directories as needed,
with their file modes unaffected by any \fB\-m\fR option
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mkdir\-v
\fB\-v, \-\-verbose\fP
.UE
print a message for each created directory
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mkdir\-Z
\fB\-Z\fP
.UE
set SELinux security context of each created directory
to the default type
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mkdir\-\-context
\fB\-\-context[=CTX]\fP
.UE
like \fB\-Z\fR, or if CTX is specified then set the
SELinux or SMACK security context to CTX
.TP
.UR https://www.gnu.org/software/coreutils/mkdir#mkdir\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/mkdir#mkdir\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.SH AUTHOR
Written by David MacKenzie.
.SH "REPORTING BUGS"
Report bugs to
.MT bug\-coreutils@gnu.org
GNU coreutils
.ME .
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
\fBmkdir\fP(2)
.PP
.br
.UR https://www.gnu.org/software/coreutils/mkdir
Full documentation online
.UE
.br
or available locally via: info \(aq(coreutils) mkdir invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
SPDX-License-Identifier:
.UR https://gnu.org/licenses/gpl.html
GPL-3.0-or-later
.UE
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
