.TH mkfifo 1 (date) "GNU coreutils (unreleased)"
.SH NAME
mkfifo \- make FIFOs (named pipes)
.SH SYNOPSIS
.SY mkfifo
.RI [ OPTION \~.\|.\|.\&]
.IR NAME \~.\|.\|.\&
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Create named pipes (FIFOs) with the given NAMEs.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mkfifo\-m
\fB\-m, \-\-mode=\,MODE\fP
.UE
set file permission bits to MODE, not a=rw \- umask
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mkfifo\-Z
\fB\-Z\fP
.UE
set the SELinux security context to default type
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mkfifo\-\-context
\fB\-\-context[=CTX]\fP
.UE
like \fB\-Z\fR, or if CTX is specified then set the
SELinux or SMACK security context to CTX
.TP
.UR https://www.gnu.org/software/coreutils/mkfifo#mkfifo\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/mkfifo#mkfifo\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.SH AUTHOR
Written by David MacKenzie.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
\fBmkfifo\fP(3)
.PP
.br
.UR https://www.gnu.org/software/coreutils/mkfifo
Full documentation online
.UE
.br
or available locally via: info \(aq(coreutils) mkfifo invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
SPDX-License-Identifier:
.UR https://gnu.org/licenses/gpl.html
GPL-3.0-or-later
.UE
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
