.TH mknod 1 (date) "GNU coreutils (unreleased)"
.SH NAME
mknod \- make block or character special files
.SH SYNOPSIS
.SY mknod
.RI [ OPTION \~.\|.\|.\&]
.I NAME
.I TYPE
.RI [ MAJOR
.IR MINOR ]
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Create the special file NAME of the given TYPE.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mknod\-m
\fB\-m, \-\-mode=\,MODE\fP
.UE
set file permission bits to MODE, not a=rw \- umask
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mknod\-Z
\fB\-Z\fP
.UE
set the SELinux security context to default type
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mknod\-\-context
\fB\-\-context[=CTX]\fP
.UE
like \fB\-Z\fR, or if CTX is specified then set the
SELinux or SMACK security context to CTX
.TP
.UR https://www.gnu.org/software/coreutils/mknod#mknod\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/mknod#mknod\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.PP
Both MAJOR and MINOR must be specified when TYPE is b, c, or u, and they
must be omitted when TYPE is p.  If MAJOR or MINOR begins with 0x or 0X,
it is interpreted as hexadecimal; otherwise, if it begins with 0, as octal;
otherwise, as decimal.  TYPE may be:
.TP
b
create a block (buffered) special file
.TP
c, u
create a character (unbuffered) special file
.TP
p
create a FIFO
.PP
Your shell may have its own version of mknod, which usually supersedes
the version described here.  Please refer to your shell's documentation
for details about the options it supports.
.SH AUTHOR
Written by David MacKenzie.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
General help using GNU software: <https://www.gnu.org/gethelp/>
.br
Report any translation bugs to <https://translationproject.org/team/>
.SH "SEE ALSO"
\fBmknod\fP(2)
.PP
.br
Full documentation <https://www.gnu.org/software/coreutils/mknod>
.br
or available locally via: info \(aq(coreutils) mknod invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
