.TH mv 1 (date) "GNU coreutils (unreleased)"
.SH NAME
mv \- move (rename) files
.SH SYNOPSIS
.SY mv
.RI [ OPTION \~.\|.\|.\&]
.RB [ \-T ]
.I SOURCE
.I DEST
.YS
.SY mv
.RI [ OPTION \~.\|.\|.\&]
.IR SOURCE \~.\|.\|.\&
.I DIRECTORY
.YS
.SY mv
.RI [ OPTION \~.\|.\|.\&]
.BI \-t\~ DIRECTORY
.IR SOURCE \~.\|.\|.\&
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Rename SOURCE to DEST, or move SOURCE(s) to DIRECTORY.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mv--backup
\fB\-\-backup[=CONTROL]\fP
.UE
make a backup of each existing destination file
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mv-b
\fB\-b\fP
.UE
like \fB\-\-backup\fR but does not accept an argument
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mv--debug
\fB\-\-debug\fP
.UE
explain how a file is copied.  Implies \fB\-v\fR
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mv--exchange
\fB\-\-exchange\fP
.UE
exchange source and destination
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mv-f
\fB\-f, \-\-force\fP
.UE
do not prompt before overwriting
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mv-i
\fB\-i, \-\-interactive\fP
.UE
prompt before overwrite
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mv-n
\fB\-n, \-\-no\-clobber\fP
.UE
do not overwrite an existing file
.PP
If you specify more than one of \fB\-i\fR, \fB\-f\fR, \fB\-n\fR, only the final one takes effect.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mv--no-copy
\fB\-\-no\-copy\fP
.UE
do not copy if renaming fails
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mv--strip-trailing-slashes
\fB\-\-strip\-trailing\-slashes\fP
.UE
remove any trailing slashes from each SOURCE argument
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mv-S
\fB\-S, \-\-suffix=\,SUFFIX\fP
.UE
override the usual backup suffix
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mv-t
\fB\-t, \-\-target\-directory=\,DIRECTORY\fP
.UE
move all SOURCE arguments into DIRECTORY
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mv-T
\fB\-T, \-\-no\-target\-directory\fP
.UE
treat DEST as a normal file
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mv--update
\fB\-\-update[=UPDATE]\fP
.UE
control which existing files are updated;
UPDATE={all,none,none\-fail,older(default)}
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mv-u
\fB\-u\fP
.UE
equivalent to \fB\-\-update\fR[=\fI\,older\/\fR].  See below
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mv-v
\fB\-v, \-\-verbose\fP
.UE
explain what is being done
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#mv-Z
\fB\-Z, \-\-context\fP
.UE
set SELinux security context of destination file to default type
.TP
.UR https://www.gnu.org/software/coreutils/mv#mv--help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/mv#mv--version
\fB\-\-version\fP
.UE
output version information and exit
.PP
UPDATE controls which existing files in the destination are replaced.
\&'all' is the default operation when an \fB\-\-update\fR option is not specified,
and results in all existing files in the destination being replaced.
\&'none' is like the \fB\-\-no\-clobber\fR option, in that no files in the
destination are replaced, and skipped files do not induce a failure.
\&'none\-fail' also ensures no files are replaced in the destination,
but any skipped files are diagnosed and induce a failure.
\&'older' is the default operation when \fB\-\-update\fR is specified, and results
in files being replaced if they're older than the corresponding source file.
.PP
The backup suffix is '~', unless set with \fB\-\-suffix\fR or SIMPLE_BACKUP_SUFFIX.
The version control method may be selected via the \fB\-\-backup\fR option or through
the VERSION_CONTROL environment variable.  Here are the values:
.TP
none, off
never make backups (even if \fB\-\-backup\fR is given)
.TP
numbered, t
make numbered backups
.TP
existing, nil
numbered if numbered backups exist, simple otherwise
.TP
simple, never
always make simple backups
.SH AUTHOR
Written by Mike Parker, David MacKenzie, and Jim Meyering.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
GNU coreutils home page: <https://www.gnu.org/software/coreutils/>
.br
General help using GNU software: <https://www.gnu.org/gethelp/>
.br
Report any translation bugs to <https://translationproject.org/team/>
.SH "SEE ALSO"
\fBrename\fP(2)
.PP
.br
Full documentation <https://www.gnu.org/software/coreutils/mv>
.br
or available locally via: info \(aq(coreutils) mv invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
