.TH nohup 1 (date) "GNU coreutils (unreleased)"
.SH NAME
nohup \- run a command immune to hangups, with output to a non-tty
.SH SYNOPSIS
.SY nohup
.I COMMAND
.RI [ ARG \~.\|.\|.\&]
.YS
.SY nohup
.I OPTION
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Run COMMAND, ignoring hangup signals.
.TP
.UR https://www.gnu.org/software/coreutils/nohup#nohup\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/nohup#nohup\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.PP
If standard input is a terminal, redirect it from an unreadable file.
If standard output is a terminal, append output to 'nohup.out' if possible,
\&'$HOME/nohup.out' otherwise.
If standard error is a terminal, redirect it to standard output.
To save output to FILE, use 'nohup COMMAND > FILE'.
.PP
Your shell may have its own version of nohup, which usually supersedes
the version described here.  Please refer to your shell's documentation
for details about the options it supports.
.SH EXIT STATUS
.TP
125
if the nohup command itself fails
.TP
126
if COMMAND is found but cannot be invoked
.TP
127
if COMMAND cannot be found
.TP
\-
the exit status of COMMAND otherwise
.SH AUTHOR
Written by Jim Meyering.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
Full documentation <https://www.gnu.org/software/coreutils/nohup>
.br
or available locally via: info \(aq(coreutils) nohup invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
