.TH nproc 1 (date) "GNU coreutils (unreleased)"
.SH NAME
nproc \- print the number of processing units available
.SH SYNOPSIS
.SY nproc
.RI [ OPTION \~.\|.\|.\&]
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Print the number of processing units available to the current process,
which may be less than the number of online processors.
If the 'OMP_NUM_THREADS' or 'OMP_THREAD_LIMIT' environment variables are set,
then they will determine the minimum and maximum returned value respectively.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#nproc\-\-all
\fB\-\-all\fP
.UE
print the number of installed processors,
disregarding any OpenMP environment variables, or CPU quotas.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#nproc\-\-ignore
\fB\-\-ignore=N\fP
.UE
if possible, exclude N processing units.
The result is guaranteed to be at least 1.
.TP
.UR https://www.gnu.org/software/coreutils/nproc#nproc\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/nproc#nproc\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.SH AUTHOR
Written by Giuseppe Scrivano.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
.UR https://www.gnu.org/software/coreutils/nproc
Full documentation online
.UE
.br
or available locally via: info \(aq(coreutils) nproc invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
