.TH paste 1 (date) "GNU coreutils (unreleased)"
.SH NAME
paste \- merge lines of files
.SH SYNOPSIS
.SY paste
.RI [ OPTION \~.\|.\|.\&]
.RI [ FILE \~.\|.\|.\&]
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Write lines consisting of the sequentially corresponding lines from
each FILE, separated by TABs, to standard output.
The newline of every line except the line from the last file
is replaced with a TAB.
.PP
With no FILE, or when FILE is \-, read standard input.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#paste\-d
\fB\-d, \-\-delimiters=\,LIST\fP
.UE
reuse characters from LIST instead of TABs;
backslash escapes are supported
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#paste\-s
\fB\-s, \-\-serial\fP
.UE
paste one file at a time instead of in parallel; the newline of
every line except the last line in each file is replaced with a TAB
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#paste\-z
\fB\-z, \-\-zero\-terminated\fP
.UE
line delimiter is NUL, not newline
.TP
.UR https://www.gnu.org/software/coreutils/paste#paste\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/paste#paste\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.SH AUTHOR
Written by David M. Ihnat and David MacKenzie.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
General help using GNU software: <https://www.gnu.org/gethelp/>
.br
Report any translation bugs to <https://translationproject.org/team/>
.SH "SEE ALSO"
Full documentation <https://www.gnu.org/software/coreutils/paste>
.br
or available locally via: info \(aq(coreutils) paste invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
