.TH pinky 1 (date) "GNU coreutils (unreleased)"
.SH NAME
pinky \- lightweight finger
.SH SYNOPSIS
.SY pinky
.RI [ OPTION \~.\|.\|.\&]
.RI [ USER \~.\|.\|.\&]
.YS
.SH DESCRIPTION
.\" Add any additional description here
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pinky\-l
\fB\-l\fP
.UE
produce long format output for the specified USERs
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pinky\-b
\fB\-b\fP
.UE
omit the user's home directory and shell in long format
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pinky\-h
\fB\-h\fP
.UE
omit the user's project file in long format
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pinky\-p
\fB\-p\fP
.UE
omit the user's plan file in long format
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pinky\-s
\fB\-s\fP
.UE
do short format output, this is the default
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pinky\-f
\fB\-f\fP
.UE
omit the line of column headings in short format
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pinky\-w
\fB\-w\fP
.UE
omit the user's full name in short format
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pinky\-i
\fB\-i\fP
.UE
omit the user's full name and remote host in short format
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pinky\-q
\fB\-q\fP
.UE
omit the user's full name, remote host and idle time in short format
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pinky\-\-lookup
\fB\-\-lookup\fP
.UE
attempt to canonicalize hostnames via DNS
.TP
.UR https://www.gnu.org/software/coreutils/pinky#pinky\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/pinky#pinky\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.PP
A lightweight 'finger' program;  print user information.
The utmp file will be \fI\,/var/run/utmp\/\fP.
.SH AUTHOR
Written by Joseph Arceneaux, David MacKenzie, and Kaveh Ghazi.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
.UR https://www.gnu.org/software/coreutils/pinky
Full documentation online
.UE
.br
or available locally via: info \(aq(coreutils) pinky invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
