.TH pr 1 (date) "GNU coreutils (unreleased)"
.SH NAME
pr \- convert text files for printing
.SH SYNOPSIS
.SY pr
.RI [ OPTION \~.\|.\|.\&]
.RI [ FILE \~.\|.\|.\&]
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Paginate or columnate FILE(s) for printing.
.PP
With no FILE, or when FILE is \-, read standard input.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pr\-\-pages
\fB+FIRST_PAGE[:LAST_PAGE], \-\-pages=\,FIRST_PAGE[:LAST_PAGE]\fP
.UE
begin [stop] printing with page FIRST_[LAST_]PAGE
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pr\-COLS
\fB\-COLS, \-\-columns=\,COLS\fP
.UE
output COLS columns and print columns down, unless \fB\-a\fR is used.
Balance number of lines in the columns on each page
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pr\-a
\fB\-a, \-\-across\fP
.UE
print columns across rather than down, used together with \fB\-COLUMN\fR
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pr\-c
\fB\-c, \-\-show\-control\-chars\fP
.UE
use hat notation (^G) and octal backslash notation
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pr\-d
\fB\-d, \-\-double\-space\fP
.UE
double space the output
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pr\-D
\fB\-D, \-\-date\-format=\,FORMAT\fP
.UE
use FORMAT for the header date
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pr\-e
\fB\-e[CHAR[WIDTH]], \-\-expand\-tabs[=\,CHAR[WIDTH]]\fP
.UE
expand input CHARs (TABs) to tab WIDTH (8)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pr\-F
\fB\-F, \-f, \-\-form\-feed\fP
.UE
use form feeds instead of newlines to separate pages
(by a 3\-line page header with \fB\-F\fR or a 5\-line header
and trailer without \fB\-F\fR)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pr\-h
\fB\-h, \-\-header=\,HEADER\fP
.UE
use a centered HEADER instead of filename in page header,
\fB\-h\fR "" prints a blank line, don't use \fB\-h\fR""
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pr\-i
\fB\-i[CHAR[WIDTH]], \-\-output\-tabs[=\,CHAR[WIDTH]]\fP
.UE
replace spaces with CHARs (TABs) to tab WIDTH (8)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pr\-J
\fB\-J, \-\-join\-lines\fP
.UE
merge full lines, turns off \fB\-W\fR line truncation,
no column alignment, \fB\-\-sep\-string\fR[=\fI\,STRING\/\fR] sets separators
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pr\-l
\fB\-l, \-\-length=\,PAGE_LENGTH\fP
.UE
set the page length to PAGE_LENGTH (66) lines
(default number of lines of text 56, and with \fB\-F\fR 63).
implies \fB\-t\fR if PAGE_LENGTH <= 10
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pr\-m
\fB\-m, \-\-merge\fP
.UE
print all files in parallel, one in each column,
truncate lines, but join lines of full length with \fB\-J\fR
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pr\-n
\fB\-n[SEP[DIGITS]], \-\-number\-lines[=\,SEP[DIGITS]]\fP
.UE
number lines, use DIGITS (5) digits, then SEP (TAB),
default counting starts with 1st line of input file
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pr\-N
\fB\-N, \-\-first\-line\-number=\,NUMBER\fP
.UE
start counting with NUMBER at 1st line of first
page printed (see +FIRST_PAGE)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pr\-o
\fB\-o, \-\-indent=\,MARGIN\fP
.UE
offset each line with MARGIN (zero) spaces, do not
affect \fB\-w\fR or \fB\-W\fR, MARGIN will be added to PAGE_WIDTH
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pr\-r
\fB\-r, \-\-no\-file\-warnings\fP
.UE
omit warning when a file cannot be opened
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pr\-s
\fB\-s[CHAR], \-\-separator[=\,CHAR]\fP
.UE
separate columns by a single character, default for CHAR
is the <TAB> character without \fB\-w\fR and 'no char' with \fB\-w\fR.
\fB\-s\fR[\fI\,CHAR\/\fR] turns off line truncation of all 3 column
options (\fB\-COLUMN\fR|\-a \fB\-COLUMN\fR|\-m) except \fB\-w\fR is set
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pr\-S
\fB\-S[STRING], \-\-sep\-string[=\,STRING]\fP
.UE
separate columns by STRING,
without \fB\-S\fR: Default separator <TAB> with \fB\-J\fR and <space>
otherwise (same as \fB\-S\fR" "), no effect on column options
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pr\-t
\fB\-t, \-\-omit\-header\fP
.UE
omit page headers and trailers; implied if PAGE_LENGTH <= 10
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pr\-T
\fB\-T, \-\-omit\-pagination\fP
.UE
omit page headers and trailers,
eliminate any pagination by form feeds set in input files
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pr\-v
\fB\-v, \-\-show\-nonprinting\fP
.UE
use octal backslash notation
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pr\-w
\fB\-w, \-\-width=\,PAGE_WIDTH\fP
.UE
set page width to PAGE_WIDTH (72) characters for
multiple text\-column output only, \fB\-s\fR[\fI\,char\/\fR] turns off (72)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pr\-W
\fB\-W, \-\-page\-width=\,PAGE_WIDTH\fP
.UE
set page width to PAGE_WIDTH (72) characters always,
truncate lines, except \fB\-J\fR option is set,
no interference with \fB\-S\fR or \fB\-s\fR
.TP
.UR https://www.gnu.org/software/coreutils/pr#pr\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/pr#pr\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.SH AUTHOR
Written by Pete TerMaat and Roland Huebner.
.SH "REPORTING BUGS"
Report bugs to
.MT bug\-coreutils@gnu.org
GNU coreutils
.ME .
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
.UR https://www.gnu.org/software/coreutils/pr
Full documentation online
.UE
.br
or available locally via: info \(aq(coreutils) pr invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
SPDX-License-Identifier:
.UR https://gnu.org/licenses/gpl.html
GPL-3.0-or-later
.UE
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
