.TH printenv 1 (date) "GNU coreutils (unreleased)"
.SH NAME
printenv \- print all or part of environment
.SH SYNOPSIS
.SY printenv
.RI [ OPTION ]
.RI [ VARIABLE \~.\|.\|.\&]
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Print the values of the specified environment VARIABLE(s).
If no VARIABLE is specified, print name and value pairs for them all.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#printenv\-0
\fB\-0, \-\-null\fP
.UE
end each output line with NUL, not newline
.TP
.UR https://www.gnu.org/software/coreutils/printenv#printenv\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/printenv#printenv\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.PP
Your shell may have its own version of printenv, which usually supersedes
the version described here.  Please refer to your shell's documentation
for details about the options it supports.
.SH AUTHOR
Written by David MacKenzie and Richard Mlynarik.
.SH "REPORTING BUGS"
Report bugs to
.MT bug\-coreutils@gnu.org
GNU coreutils
.ME .
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
.UR https://www.gnu.org/software/coreutils/printenv
Full documentation online
.UE
.br
or available locally via: info \(aq(coreutils) printenv invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
SPDX-License-Identifier:
.UR https://gnu.org/licenses/gpl.html
GPL-3.0-or-later
.UE
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
