.TH pwd 1 (date) "GNU coreutils (unreleased)"
.SH NAME
pwd \- print name of current/working directory
.SH SYNOPSIS
.SY pwd
.RI [ OPTION \~.\|.\|.\&]
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Print the full filename of the current working directory.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pwd\-L
\fB\-L, \-\-logical\fP
.UE
use PWD from environment, even if it contains symlinks
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#pwd\-P
\fB\-P, \-\-physical\fP
.UE
resolve all symlinks
.TP
.UR https://www.gnu.org/software/coreutils/pwd#pwd\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/pwd#pwd\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.PP
If no option is specified, \fB\-P\fR is assumed.
.PP
Your shell may have its own version of pwd, which usually supersedes
the version described here.  Please refer to your shell's documentation
for details about the options it supports.
.SH AUTHOR
Written by Jim Meyering.
.SH "REPORTING BUGS"
Report bugs to
.MT bug\-coreutils@gnu.org
GNU coreutils
.ME .
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
\fBgetcwd\fP(3)
.PP
.br
.UR https://www.gnu.org/software/coreutils/pwd
Full documentation online
.UE
.br
or available locally via: info \(aq(coreutils) pwd invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
SPDX-License-Identifier:
.UR https://gnu.org/licenses/gpl.html
GPL-3.0-or-later
.UE
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
