.TH readlink 1 (date) "GNU coreutils (unreleased)"
.SH NAME
readlink \- print resolved symbolic links or canonical file names
.SH SYNOPSIS
.SY readlink
.RI [ OPTION \~.\|.\|.\&]
.IR FILE \~.\|.\|.\&
.YS
.SH DESCRIPTION
.\" Add any additional description here
\fBrealpath\fP(1) is a better command
for canonicalization functionality.
.PP
Print value of a symbolic link or canonical file name
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#readlink\-f
\fB\-f, \-\-canonicalize\fP
.UE
canonicalize by following every symlink
in every component of the given name recursively;
all but the last component must exist
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#readlink\-e
\fB\-e, \-\-canonicalize\-existing\fP
.UE
canonicalize by following every symlink
in every component of the given name recursively;
all components must exist
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#readlink\-m
\fB\-m, \-\-canonicalize\-missing\fP
.UE
canonicalize by following every symlink
in every component of the given name recursively,
without requirements on components existence
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#readlink\-n
\fB\-n, \-\-no\-newline\fP
.UE
do not output the trailing delimiter
.HP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#readlink\-q
\fB\-q, \-\-quiet\fP
.UE
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#readlink\-s
\fB\-s, \-\-silent\fP
.UE
suppress most error messages
(on by default if POSIXLY_CORRECT is not set)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#readlink\-v
\fB\-v, \-\-verbose\fP
.UE
report error messages
(on by default if POSIXLY_CORRECT is set)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#readlink\-z
\fB\-z, \-\-zero\fP
.UE
end each output line with NUL, not newline
.TP
.UR https://www.gnu.org/software/coreutils/readlink#readlink\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/readlink#readlink\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.SH AUTHOR
Written by Dmitry V. Levin.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
\fBreadlink\fP(2), \fBrealpath\fP(1), \fBrealpath\fP(3)
.PP
.br
.UR https://www.gnu.org/software/coreutils/readlink
Full documentation online
.UE
.br
or available locally via: info \(aq(coreutils) readlink invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
