.TH realpath 1 (date) "GNU coreutils (unreleased)"
.SH NAME
realpath \- print the resolved path
.SH SYNOPSIS
.SY realpath
.RI [ OPTION \~.\|.\|.\&]
.IR FILE \~.\|.\|.\&
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Print the resolved absolute file name.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#realpath\-E
\fB\-E, \-\-canonicalize\fP
.UE
all but the last component must exist (default)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#realpath\-e
\fB\-e, \-\-canonicalize\-existing\fP
.UE
all components of the path must exist
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#realpath\-m
\fB\-m, \-\-canonicalize\-missing\fP
.UE
no path components need exist or be a directory
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#realpath\-L
\fB\-L, \-\-logical\fP
.UE
resolve '..' components before symlinks
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#realpath\-P
\fB\-P, \-\-physical\fP
.UE
resolve symlinks as encountered (default)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#realpath\-q
\fB\-q, \-\-quiet\fP
.UE
suppress most error messages
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#realpath\-\-relative\-to
\fB\-\-relative\-to=DIR\fP
.UE
print the resolved path relative to DIR
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#realpath\-\-relative\-base
\fB\-\-relative\-base=DIR\fP
.UE
print absolute paths unless paths below DIR
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#realpath\-s
\fB\-s, \-\-strip, \-\-no\-symlinks\fP
.UE
don't expand symlinks
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#realpath\-z
\fB\-z, \-\-zero\fP
.UE
end each output line with NUL, not newline
.TP
.UR https://www.gnu.org/software/coreutils/realpath#realpath\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/realpath#realpath\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.SH AUTHOR
Written by Padraig Brady.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
\fBreadlink\fP(1), \fBreadlink\fP(2), \fBrealpath\fP(3)
.PP
.br
.UR https://www.gnu.org/software/coreutils/realpath
Full documentation online
.UE
.br
or available locally via: info \(aq(coreutils) realpath invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
SPDX-License-Identifier:
.UR https://gnu.org/licenses/gpl.html
GPL-3.0-or-later
.UE
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
