.TH rm 1 (date) "GNU coreutils (unreleased)"
.SH NAME
rm \- remove files or directories
.SH SYNOPSIS
.SY rm
.RI [ OPTION \~.\|.\|.\&]
.RI [ FILE \~.\|.\|.\&]
.YS
.SH DESCRIPTION
This manual page
documents the GNU version of
.BR rm .
.B rm
removes each specified file.  By default, it does not remove
directories.
.P
If the \fI\-I\fR or \fI\-\-interactive=once\fR option is given,
and there are more than three files or the \fI\-r\fR, \fI\-R\fR,
or \fI\-\-recursive\fR are given, then
.B rm
prompts the user for whether to proceed with the entire operation.  If
the response is not affirmative, the entire command is aborted.
.P
Otherwise, if a file is unwritable, standard input is a terminal, and
the \fI\-f\fR or \fI\-\-force\fR option is not given, or the
\fI\-i\fR or \fI\-\-interactive=always\fR option is given,
.B rm
prompts the user for whether to remove the file.  If the response is
not affirmative, the file is skipped.
.SH OPTIONS
.PP
Remove (unlink) the FILE(s).
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#rm\-f
\fB\-f, \-\-force\fP
.UE
ignore nonexistent files and arguments, never prompt
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#rm\-i
\fB\-i\fP
.UE
prompt before every removal
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#rm\-I
\fB\-I\fP
.UE
prompt once before removing more than three files,
or when removing recursively; less intrusive than \fB\-i\fR,
while still giving protection against most mistakes
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#rm\-\-interactive
\fB\-\-interactive[=WHEN]\fP
.UE
prompt according to WHEN: never, once (\fB\-I\fR), or always (\fB\-i\fR);
without WHEN, prompt always
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#rm\-\-one\-file\-system
\fB\-\-one\-file\-system\fP
.UE
when removing a hierarchy recursively,
skip any directory that is on a file system different
from that of the corresponding command line argument
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#rm\-\-no\-preserve\-root
\fB\-\-no\-preserve\-root\fP
.UE
do not treat '/' specially
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#rm\-\-preserve\-root
\fB\-\-preserve\-root[=all]\fP
.UE
do not remove '/' (default);
with 'all', reject any command line argument
on a separate device from its parent
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#rm\-r
\fB\-r, \-R, \-\-recursive\fP
.UE
remove directories and their contents recursively
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#rm\-d
\fB\-d, \-\-dir\fP
.UE
remove empty directories
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#rm\-v
\fB\-v, \-\-verbose\fP
.UE
explain what is being done
.TP
.UR https://www.gnu.org/software/coreutils/rm#rm\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/rm#rm\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.PP
By default, rm does not remove directories.  Use the \fB\-\-recursive\fR (\fB\-r\fR or \fB\-R\fR)
option to remove each listed directory, too, along with all of its contents.
.PP
Any attempt to remove a file whose last file name component is '.' or '..'
is rejected with a diagnostic.
.PP
To remove a file whose name starts with a '\-', for example '\-foo',
use one of these commands:
.IP
rm \fB\-\-\fR \fB\-foo\fR
.IP
rm ./\-foo
.PP
If you use rm to remove a file, it might be possible to recover
some of its contents, given sufficient expertise and/or time.  For greater
assurance that the contents are unrecoverable, consider using \fBshred\fP(1).
.SH AUTHOR
Written by Paul Rubin, David MacKenzie, Richard M. Stallman,
and Jim Meyering.
.SH "REPORTING BUGS"
Report bugs to
.MT bug\-coreutils@gnu.org
GNU coreutils
.ME .
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
\fBunlink\fP(1), \fBunlink\fP(2), \fBchattr\fP(1), \fBshred\fP(1)
.PP
.br
.UR https://www.gnu.org/software/coreutils/rm
Full documentation online
.UE
.br
or available locally via: info \(aq(coreutils) rm invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
SPDX-License-Identifier:
.UR https://gnu.org/licenses/gpl.html
GPL-3.0-or-later
.UE
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
