.TH rmdir 1 (date) "GNU coreutils (unreleased)"
.SH NAME
rmdir \- remove empty directories
.SH SYNOPSIS
.SY rmdir
.RI [ OPTION \~.\|.\|.\&]
.IR DIRECTORY \~.\|.\|.\&
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Remove the DIRECTORY(ies), if they are empty.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#rmdir\-\-ignore\-fail\-on\-non\-empty
\fB\-\-ignore\-fail\-on\-non\-empty\fP
.UE
ignore each failure to remove a non\-empty directory
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#rmdir\-p
\fB\-p, \-\-parents\fP
.UE
remove DIRECTORY and its ancestors;
e.g., 'rmdir \fB\-p\fR a/b' is similar to 'rmdir a/b a'
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#rmdir\-v
\fB\-v, \-\-verbose\fP
.UE
output a diagnostic for every directory processed
.TP
.UR https://www.gnu.org/software/coreutils/rmdir#rmdir\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/rmdir#rmdir\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.SH AUTHOR
Written by David MacKenzie.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
General help using GNU software: <https://www.gnu.org/gethelp/>
.br
Report any translation bugs to <https://translationproject.org/team/>
.SH "SEE ALSO"
\fBrmdir\fP(2)
.PP
.br
Full documentation <https://www.gnu.org/software/coreutils/rmdir>
.br
or available locally via: info \(aq(coreutils) rmdir invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
