.TH seq 1 (date) "GNU coreutils (unreleased)"
.SH NAME
seq \- print a sequence of numbers
.SH SYNOPSIS
.SY seq
.RI [ OPTION \~.\|.\|.\&]
.I LAST
.YS
.SY seq
.RI [ OPTION \~.\|.\|.\&]
.I FIRST
.I LAST
.YS
.SY seq
.RI [ OPTION \~.\|.\|.\&]
.I FIRST
.I INCREMENT
.I LAST
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Print numbers from FIRST to LAST, in steps of INCREMENT.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#seq\-f
\fB\-f, \-\-format=\,FORMAT\fP
.UE
use printf style floating\-point FORMAT
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#seq\-s
\fB\-s, \-\-separator=\,STRING\fP
.UE
use STRING to separate numbers (default: \en)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#seq\-w
\fB\-w, \-\-equal\-width\fP
.UE
equalize width by padding with leading zeroes
.TP
.UR https://www.gnu.org/software/coreutils/seq#seq\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/seq#seq\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.PP
If FIRST or INCREMENT is omitted, it defaults to 1.  That is, an
omitted INCREMENT defaults to 1 even when LAST is smaller than FIRST.
The sequence of numbers ends when the sum of the current number and
INCREMENT would become greater than LAST.
FIRST, INCREMENT, and LAST are interpreted as floating point values.
INCREMENT is usually positive if FIRST is smaller than LAST, and
INCREMENT is usually negative if FIRST is greater than LAST.
INCREMENT must not be 0; none of FIRST, INCREMENT and LAST may be NaN.
FORMAT must be suitable for printing one argument of type 'double';
it defaults to %.PRECf if FIRST, INCREMENT, and LAST are all fixed point
decimal numbers with maximum precision PREC, and to %g otherwise.
.SH AUTHOR
Written by Ulrich Drepper.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
.UR https://www.gnu.org/software/coreutils/seq
Full documentation online
.UE
.br
or available locally via: info \(aq(coreutils) seq invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
SPDX-License-Identifier:
.UR https://gnu.org/licenses/gpl.html
GPL-3.0-or-later
.UE
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
