.TH shred 1 (date) "GNU coreutils (unreleased)"
.SH NAME
shred \- overwrite a file to hide its contents, and optionally delete it
.SH SYNOPSIS
.SY shred
.RI [ OPTION \~.\|.\|.\&]
.IR FILE \~.\|.\|.\&
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Overwrite the specified FILE(s) repeatedly, in order to make it harder
for even very expensive hardware probing to recover the data.
.PP
If FILE is \-, shred standard output.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#shred\-f
\fB\-f, \-\-force\fP
.UE
change permissions to allow writing if necessary
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#shred\-n
\fB\-n, \-\-iterations=\,N\fP
.UE
overwrite N times instead of the default (3)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#shred\-\-random\-source
\fB\-\-random\-source=FILE\fP
.UE
get random bytes from FILE
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#shred\-s
\fB\-s, \-\-size=\,N\fP
.UE
shred this many bytes (suffixes like K, M, G accepted)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#shred\-u
\fB\-u\fP
.UE
deallocate and remove file after overwriting
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#shred\-\-remove
\fB\-\-remove[=HOW]\fP
.UE
like \fB\-u\fR but give control on HOW to delete;  See below
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#shred\-v
\fB\-v, \-\-verbose\fP
.UE
show details of data and metadata operations performed
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#shred\-x
\fB\-x, \-\-exact\fP
.UE
do not round file sizes up to the next full block;
this is the default for non\-regular files
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#shred\-z
\fB\-z, \-\-zero\fP
.UE
add a final overwrite with zeros to hide shredding
.TP
.UR https://www.gnu.org/software/coreutils/shred#shred\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/shred#shred\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.PP
Delete FILE(s) if \fB\-\-remove\fR (\fB\-u\fR) is specified.  The default is not to remove
the files because it is common to operate on device files like \fI\,/dev/hda\/\fP,
and those files usually should not be removed.
The optional HOW parameter indicates how to remove a directory entry:
\&'unlink' => use a standard unlink call.
\&'wipe' => also first obfuscate bytes in the name.
\&'wipesync' => also sync each obfuscated byte to the device.
The default mode is 'wipesync', but note it can be expensive.
.PP
CAUTION: shred assumes the file system and hardware overwrite data in place.
Although this is common, many platforms operate otherwise.  Also, backups
and mirrors may contain unremovable copies that will let a shredded file
be recovered later.  See the GNU coreutils manual for details.
.SH AUTHOR
Written by Colin Plumb.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
GNU coreutils home page: <https://www.gnu.org/software/coreutils/>
.br
General help using GNU software: <https://www.gnu.org/gethelp/>
.br
Report any translation bugs to <https://translationproject.org/team/>
.SH "SEE ALSO"
Full documentation <https://www.gnu.org/software/coreutils/shred>
.br
or available locally via: info \(aq(coreutils) shred invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
