.TH sum 1 (date) "GNU coreutils (unreleased)"
.SH NAME
sum \- checksum and count the blocks in a file
.SH SYNOPSIS
.SY sum
.RI [ OPTION \~.\|.\|.\&]
.RI [ FILE \~.\|.\|.\&]
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Print or check BSD (16\-bit) checksums.
Legacy interface to the cksum utility.
.PP
With no FILE, or when FILE is \-, read standard input.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#sum\-r
\fB\-r\fP
.UE
use BSD sum algorithm (the default), use 1K blocks
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#sum\-s
\fB\-s, \-\-sysv\fP
.UE
use System V sum algorithm, use 512 bytes blocks
.TP
.UR https://www.gnu.org/software/coreutils/sum#sum\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/sum#sum\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.SH AUTHOR
Written by Kayvan Aghaiepour and David MacKenzie.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to <https://translationproject.org/team/>
.SH "SEE ALSO"
Full documentation <https://www.gnu.org/software/coreutils/sum>
.br
or available locally via: info \(aq(coreutils) sum invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
