.TH SYNC 1 (date) "GNU coreutils (unreleased)"
.SH NAME
sync \- Synchronize cached writes to persistent storage
.SH SYNOPSIS
.B sync
[\fI\,OPTION\/\fR] [\fI\,FILE\/\fR]...
.SH DESCRIPTION
.\" Add any additional description here
.PP
Synchronize cached writes to persistent storage
.PP
If one or more files are specified, sync only them,
or their containing file systems.
.TP
\X'tty: link https://www.gnu.org/software/coreutils/manual/coreutils.html#sync-d'\fB\-d, \-\-data\fP\X'tty: link'
sync only file data, no unneeded metadata
.TP
\X'tty: link https://www.gnu.org/software/coreutils/manual/coreutils.html#sync-f'\fB\-f, \-\-file\-system\fP\X'tty: link'
sync the file systems that contain the files
.TP
\X'tty: link https://www.gnu.org/software/coreutils/sync#sync--help'\fB\-\-help\fP\X'tty: link'
display this help and exit
.TP
\X'tty: link https://www.gnu.org/software/coreutils/sync#sync--version'\fB\-\-version\fP\X'tty: link'
output version information and exit
.SH BUGS
Persistence guarantees vary per system.
See the system calls below for more details.
.SH AUTHOR
Written by Jim Meyering and Giuseppe Scrivano.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
GNU coreutils home page: <https://www.gnu.org/software/coreutils/>
.br
General help using GNU software: <https://www.gnu.org/gethelp/>
.br
Report any translation bugs to <https://translationproject.org/team/>
.SH "SEE ALSO"
\fBfdatasync\fP(2), \fBfsync\fP(2), \fBsync\fP(2), \fBsyncfs\fP(2)
.PP
.br
Full documentation <https://www.gnu.org/software/coreutils/sync>
.br
or available locally via: info \(aq(coreutils) sync invocation\(aq
.PP
.br
Packaged by Devuan (9.10\-1devuan1)
.br
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
