.TH sync 1 (date) "GNU coreutils (unreleased)"
.SH NAME
sync \- Synchronize cached writes to persistent storage
.SH SYNOPSIS
.SY sync
.RI [ OPTION \~.\|.\|.\&]
.RI [ FILE \~.\|.\|.\&]
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Synchronize cached writes to persistent storage
.PP
If one or more files are specified, sync only them,
or their containing file systems.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#sync\-d
\fB\-d, \-\-data\fP
.UE
sync only file data, no unneeded metadata
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#sync\-f
\fB\-f, \-\-file\-system\fP
.UE
sync the file systems that contain the files
.TP
.UR https://www.gnu.org/software/coreutils/sync#sync\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/sync#sync\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.SH BUGS
Persistence guarantees vary per system.
See the system calls below for more details.
.SH AUTHOR
Written by Jim Meyering and Giuseppe Scrivano.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
\fBfdatasync\fP(2), \fBfsync\fP(2), \fBsync\fP(2), \fBsyncfs\fP(2)
.PP
.br
.UR https://www.gnu.org/software/coreutils/sync
Full documentation online
.UE
.br
or available locally via: info \(aq(coreutils) sync invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
