.TH tac 1 (date) "GNU coreutils (unreleased)"
.SH NAME
tac \- concatenate and print files in reverse
.SH SYNOPSIS
.SY tac
.RI [ OPTION \~.\|.\|.\&]
.RI [ FILE \~.\|.\|.\&]
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Write each FILE to standard output, last line first.
.PP
With no FILE, or when FILE is \-, read standard input.
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#tac\-b
\fB\-b, \-\-before\fP
.UE
attach the separator before instead of after
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#tac\-r
\fB\-r, \-\-regex\fP
.UE
interpret the separator as a regular expression
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#tac\-s
\fB\-s, \-\-separator=\,STRING\fP
.UE
use STRING as the separator instead of newline
.TP
.UR https://www.gnu.org/software/coreutils/tac#tac\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/tac#tac\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.PP
Non\-seekable input is buffered to $TMPDIR, defaulting to \fI\,/tmp\/\fP.
.SH AUTHOR
Written by Jay Lepreau and David MacKenzie.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
\fBcat\fP(1), \fBrev\fP(1)
.PP
.br
.UR https://www.gnu.org/software/coreutils/tac
Full documentation online
.UE
.br
or available locally via: info \(aq(coreutils) tac invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
