.TH tee 1 (date) "GNU coreutils (unreleased)"
.SH NAME
tee \- read from standard input and write to standard output and files
.SH SYNOPSIS
.SY tee
.RI [ OPTION \~.\|.\|.\&]
.RI [ FILE \~.\|.\|.\&]
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Copy standard input to each FILE, and also to standard output.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#tee\-a
\fB\-a, \-\-append\fP
.UE
append to the given FILEs, do not overwrite
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#tee\-i
\fB\-i, \-\-ignore\-interrupts\fP
.UE
ignore interrupt signals
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#tee\-p
\fB\-p\fP
.UE
operate in a more appropriate MODE with pipes
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#tee\-\-output\-error
\fB\-\-output\-error[=MODE]\fP
.UE
set behavior on write error.  See MODE below
.TP
.UR https://www.gnu.org/software/coreutils/tee#tee\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/tee#tee\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.SS "MODE determines behavior with write errors on the outputs:"
.TP
warn
diagnose errors writing to any output
.TP
warn\-nopipe
diagnose errors writing to any output not a pipe
.TP
exit
exit on error writing to any output
.TP
exit\-nopipe
exit on error writing to any output not a pipe
.PP
The default MODE for the \fB\-p\fR option is 'warn\-nopipe'.
With "nopipe" MODEs, exit immediately if all outputs become broken pipes.
The default operation when \fB\-\-output\-error\fR is not specified, is to
exit immediately on error writing to a pipe, and diagnose errors
writing to non pipe outputs.
.SH AUTHOR
Written by Mike Parker, Richard M. Stallman, and David MacKenzie.
.SH "REPORTING BUGS"
Report bugs to
.MT bug\-coreutils@gnu.org
GNU coreutils
.ME .
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
.UR https://www.gnu.org/software/coreutils/tee
Full documentation online
.UE
.br
or available locally via: info \(aq(coreutils) tee invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
SPDX-License-Identifier:
.UR https://gnu.org/licenses/gpl.html
GPL-3.0-or-later
.UE
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
