.TH TTY "1" (date) "GNU coreutils (unreleased)"
.SH NAME
tty \- print the file name of the terminal connected to standard input
.SH SYNOPSIS
.B tty
[\fI\,OPTION\/\fR]...
.SH DESCRIPTION
.\" Add any additional description here
.PP
Print the file name of the terminal connected to standard input.
.TP
\X'tty: link https://www.gnu.org/software/coreutils/manual/coreutils.html#tty-s'\fB\-s, \-\-silent, \-\-quiet\fP\X'tty: link'
print nothing, only return an exit status
.TP
\X'tty: link https://www.gnu.org/software/coreutils/tty#tty--help'\fB\-\-help\fP\X'tty: link'
display this help and exit
.TP
\X'tty: link https://www.gnu.org/software/coreutils/tty#tty--version'\fB\-\-version\fP\X'tty: link'
output version information and exit
.SH AUTHOR
Written by David MacKenzie.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
GNU coreutils home page: <https://www.gnu.org/software/coreutils/>
.br
General help using GNU software: <https://www.gnu.org/gethelp/>
.br
Report any translation bugs to <https://translationproject.org/team/>
.SH "SEE ALSO"
Full documentation <https://www.gnu.org/software/coreutils/tty>
.br
or available locally via: info \(aq(coreutils) tty invocation\(aq
.PP
.br
Packaged by Devuan (9.10\-1devuan1)
.br
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
