.TH uname 1 (date) "GNU coreutils (unreleased)"
.SH NAME
uname \- print system information
.SH SYNOPSIS
.SY uname
.RI [ OPTION \~.\|.\|.\&]
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Print certain system information.  With no OPTION, same as \fB\-s\fR.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#uname\-a
\fB\-a, \-\-all\fP
.UE
print all information, in the following order,
except omit \fB\-p\fR and \fB\-i\fR if unknown
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#uname\-s
\fB\-s, \-\-kernel\-name\fP
.UE
print the kernel name
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#uname\-n
\fB\-n, \-\-nodename\fP
.UE
print the network node hostname
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#uname\-r
\fB\-r, \-\-kernel\-release\fP
.UE
print the kernel release
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#uname\-v
\fB\-v, \-\-kernel\-version\fP
.UE
print the kernel version
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#uname\-m
\fB\-m, \-\-machine\fP
.UE
print the machine hardware name
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#uname\-p
\fB\-p, \-\-processor\fP
.UE
print the processor type (non\-portable)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#uname\-i
\fB\-i, \-\-hardware\-platform\fP
.UE
print the hardware platform (non\-portable)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#uname\-o
\fB\-o, \-\-operating\-system\fP
.UE
print the operating system
.TP
.UR https://www.gnu.org/software/coreutils/uname#uname\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/uname#uname\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.SH AUTHOR
Written by David MacKenzie.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to <https://translationproject.org/team/>
.SH "SEE ALSO"
\fBarch\fP(1), \fBuname\fP(2)
.PP
.br
Full documentation <https://www.gnu.org/software/coreutils/uname>
.br
or available locally via: info \(aq(coreutils) uname invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
