.TH users 1 (date) "GNU coreutils (unreleased)"
.SH NAME
users \- print the user names of users currently logged in to the current host
.SH SYNOPSIS
.SY users
.RI [ OPTION \~.\|.\|.\&]
.RI [ FILE \~.\|.\|.\&]
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Output who is currently logged in according to FILE.
If FILE is not specified, use \fI\,/var/run/utmp\/\fP.  \fI\,/var/log/wtmp\/\fP as FILE is common.
.TP
.UR https://www.gnu.org/software/coreutils/users#users\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/users#users\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.SH AUTHOR
Written by Joseph Arceneaux and David MacKenzie.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
General help using GNU software: <https://www.gnu.org/gethelp/>
.br
Report any translation bugs to <https://translationproject.org/team/>
.SH "SEE ALSO"
\fBgetent\fP(1), \fBwho\fP(1)
.PP
.br
Full documentation <https://www.gnu.org/software/coreutils/users>
.br
or available locally via: info \(aq(coreutils) users invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
