.TH vdir 1 (date) "GNU coreutils (unreleased)"
.SH NAME
vdir \- list directory contents
.SH SYNOPSIS
.SY vdir
.RI [ OPTION \~.\|.\|.\&]
.RI [ FILE \~.\|.\|.\&]
.YS
.SH DESCRIPTION
.B vdir
is equivalent to
.IR ls\~\-l\~\-b .
.P
See
.BR ls (1).
.SH AUTHOR
Written by Richard M. Stallman and David MacKenzie.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
GNU coreutils home page: <https://www.gnu.org/software/coreutils/>
.br
General help using GNU software: <https://www.gnu.org/gethelp/>
.br
Report any translation bugs to <https://translationproject.org/team/>
.SH "SEE ALSO"
.BR ls (1),
.BR dircolors (1)
.PP
.br
Full documentation <https://www.gnu.org/software/coreutils/vdir>
.br
or available locally via: info \(aq(coreutils) vdir invocation\(aq
.PP
.br
Copyright \(co 2026 Free Software Foundation, Inc.
.br
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
