.TH who 1 (date) "GNU coreutils (unreleased)"
.SH NAME
who \- show who is logged on
.SH SYNOPSIS
.SY who
.RI [ OPTION \~.\|.\|.\&]
.RI [ FILE
|
.I ARG1
.IR ARG2 ]
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Print information about users who are currently logged in.
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#who\-a
\fB\-a, \-\-all\fP
.UE
same as \fB\-b\fR \fB\-d\fR \fB\-\-login\fR \fB\-p\fR \fB\-r\fR \fB\-t\fR \fB\-T\fR \fB\-u\fR
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#who\-b
\fB\-b, \-\-boot\fP
.UE
time of last system boot
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#who\-d
\fB\-d, \-\-dead\fP
.UE
print dead processes
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#who\-H
\fB\-H, \-\-heading\fP
.UE
print line of column headings
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#who\-l
\fB\-l, \-\-login\fP
.UE
print system login processes
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#who\-\-lookup
\fB\-\-lookup\fP
.UE
attempt to canonicalize hostnames via DNS
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#who\-m
\fB\-m\fP
.UE
only hostname and user associated with standard input
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#who\-p
\fB\-p, \-\-process\fP
.UE
print active processes spawned by init
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#who\-q
\fB\-q, \-\-count\fP
.UE
all login names and number of users logged on
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#who\-r
\fB\-r, \-\-runlevel\fP
.UE
print current runlevel
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#who\-s
\fB\-s, \-\-short\fP
.UE
print only name, line, and time (default)
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#who\-t
\fB\-t, \-\-time\fP
.UE
print last system clock change
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#who\-T
\fB\-T, \-w, \-\-mesg\fP
.UE
add user's message status as +, \- or ?
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#who\-u
\fB\-u, \-\-users\fP
.UE
list users logged in, including idle time
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#who\-\-message
\fB\-\-message\fP
.UE
same as \fB\-T\fR
.TP
.UR https://www.gnu.org/software/coreutils/manual/coreutils.html#who\-\-writable
\fB\-\-writable\fP
.UE
same as \fB\-T\fR
.TP
.UR https://www.gnu.org/software/coreutils/who#who\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/who#who\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.PP
If FILE is not specified, use \fI\,/var/run/utmp\/\fP.  \fI\,/var/log/wtmp\/\fP as FILE is common.
If ARG1 ARG2 given, \fB\-m\fR presumed: 'am i' or 'mom likes' are usual.
.SH AUTHOR
Written by Joseph Arceneaux, David MacKenzie, and Michael Stone.
.SH "REPORTING BUGS"
Report bugs to: bug\-coreutils@gnu.org
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
.UR https://www.gnu.org/software/coreutils/who
Full documentation online
.UE
.br
or available locally via: info \(aq(coreutils) who invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
SPDX-License-Identifier:
.UR https://gnu.org/licenses/gpl.html
GPL-3.0-or-later
.UE
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
