.TH whoami 1 (date) "GNU coreutils (unreleased)"
.SH NAME
whoami \- print effective user name
.SH SYNOPSIS
.SY whoami
.RI [ OPTION \~.\|.\|.\&]
.YS
.SH DESCRIPTION
.\" Add any additional description here
.PP
Print the user name associated with the current effective user ID.
Same as id \fB\-un\fR.
.TP
.UR https://www.gnu.org/software/coreutils/whoami#whoami\-\-help
\fB\-\-help\fP
.UE
display this help and exit
.TP
.UR https://www.gnu.org/software/coreutils/whoami#whoami\-\-version
\fB\-\-version\fP
.UE
output version information and exit
.SH AUTHOR
Written by Richard Mlynarik.
.SH "REPORTING BUGS"
Report bugs to
.MT bug\-coreutils@gnu.org
GNU coreutils
.ME .
.br
.UR https://www.gnu.org/software/coreutils/
GNU coreutils home page
.UE
.br
.UR https://www.gnu.org/gethelp/
General help using GNU software
.UE
.br
Report any translation bugs to
.UR https://translationproject.org/team/
the Translation Project
.UE .
.SH "SEE ALSO"
.UR https://www.gnu.org/software/coreutils/whoami
Full documentation online
.UE
.br
or available locally via: info \(aq(coreutils) whoami invocation\(aq
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
SPDX-License-Identifier:
.UR https://gnu.org/licenses/gpl.html
GPL-3.0-or-later
.UE
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
